name: Forum API Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "forum-api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: forum-api

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FORUM_API_SSH_HOST }}
          username: ${{ secrets.FORUM_API_SSH_USERNAME }}
          key: ${{ secrets.FORUM_API_SSH_KEY }}
          port: ${{ secrets.FORUM_API_SSH_PORT }}
          script: |
            cd /repos/dicoding-submission/forum-api
            sudo git pull
            sudo npm ci
            sudo npm run build
            sudo npm run migrate up
            sudo pm2 restart forum-api
