name: Forum API Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - "forum-api/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: forum-api

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: forumapi_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm run migrate up
          npm test
        env:
          CI: true
          HOST: localhost
          PORT: 5000
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: forumapi_test
          PGPASSWORD: mysecretpassword
          PGPORT: 5432
          ACCESS_TOKEN_KEY: secret
          REFRESH_TOKEN_KEY: rahasia
          ACCCESS_TOKEN_AGE: 3600
