name: Forum API Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "forum-api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: forum-api

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FORUM_API_SSH_HOST }}
          username: ${{ secrets.FORUM_API_SSH_USERNAME }}
          key: ${{ secrets.FORUM_API_SSH_KEY }}
          port: ${{ secrets.FORUM_API_SSH_PORT }}
          script: |
            cd /home/ASUS/repos/dicoding-submission/forum-api
            git pull
            npm ci
            npm run build
            npm run migrate up
            pm2 restart forum-api
